### ISSUE TITLE
React Router 4.0.0 - Alpha

### ISSUE THREAD

**Issue by saqbach** [tylermcginnis/react-router-firebase-auth#13]
I tried implementing this in a new build using a fresh copy of create-react-app. For those who might be doing something similar, you'll need to update react-router in package.json to the 4.0.0-alpha. I wasn't able to drill down and figure out exactly why that's the case, but I spent a good hour trying to figure out why it wasn't working. 

Side note: Thanks Tyler for putting this together.

**Comment by tylermcginnis** [comment]
So this will actually get updated to 4.0 beta once it's released here in the next few days.
