### ISSUE TITLE
Console error when I initialize the project

### ISSUE THREAD

**Issue by davidprati** [tylermcginnis/react-router-firebase-auth#15]
Hey, I follow the instructions and fill the constants.js file, but I have these errors, and can't find a solution :/

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of App`

And 

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of App` at App.js l21

**Comment by mocon** [comment]
I am also having this issue.

**Comment by archae0pteryx** [comment]
Yup...

**Comment by juliaogris** [comment]
Seems like this might be related to the react-router API changes  in 4.0.0-beta.6.

I've shameless stolen from this repo and the new [react-router docs](https://github.com/tylermcginnis/react-router-firebase-auth) and created my own version:
  * [Demo](https://routing-bddc6.firebaseapp.com)
  * [Code](https://github.com/juliaogris/reactrouter-firebaseauth)

**Comment by archae0pteryx** [comment]
good on you for doing this much! ima take a look at the build when i've got a sec and see if we can't get this baby back on track!

**Comment by tylermcginnis** [comment]
Hi everyone. Sorry for the delay here. Ironically Ryan and Michael (React Router devs) are my business partners so don't tell them I haven't updated this repo yet! I'll get to it within the next few days :)

**Comment by tylermcginnis** [comment]
Fixed. https://github.com/tylermcginnis/react-router-firebase-auth/commit/ddd308702d25645e7a7af6d20dfa4f771b9ca4ac
