### ISSUE TITLE
strategy for elevating firebase state

### ISSUE THREAD

**Issue by dotnwat** [tylermcginnis/react-router-firebase-auth#21]
Thank you for putting together this repository, it has been really helpful to me getting started.

This is probably a very basic question, but I'm curious about what a good strategy is for sharing Firebase state with components (avoiding redux, etc...):

For instance in this project the root component grabs the auth state with `onAuthStateChanged`, but it seems like in a Firebase app a lot of sub-components may want to use `user.uid` in Firebase queries. Should this state be passed down to components through `<Route>` or is there a way to short-circuit the React machinery and reach directly into `re-base`/`Firebase` for such global state?

Thanks

**Comment by tylermcginnis** [comment]
Have you looked at Context? https://facebook.github.io/react/docs/context.html. That's actually the exact use case for what you described.

**Comment by dotnwat** [comment]
Context was not on my radar, but that is working now for my use case. The warnings about not using that feature on that page are concerning, though. Thanks a lot for the pointer.
