### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by engr-ahsan** [tylermcginnis/react-router-firebase-auth#27]
On following your code, upon building I am getting the following error on ...rest argument. Please see the image for reference.  Please help in resolving this issue. 
![screen shot 2017-06-29 at 6 34 33 pm](https://user-images.githubusercontent.com/13553103/27690139-e6437e4a-5cf9-11e7-9324-01f5b5ef8d09.png)

**Comment by hauptrolle** [comment]
Do you have `babel-plugin-transform-object-rest-spread` installed and added to your .babelrc?
https://babeljs.io/docs/plugins/transform-object-rest-spread/
