### ISSUE TITLE
How to make this really protected?

### ISSUE THREAD

**Issue by cyberorigami** [tylermcginnis/react-router-firebase-auth#29]
If someone changes authed state to true using dev tool, it shows protected component, how can we make this more protected?

**Comment by ghost** [comment]
I disable the react dev tools when in production

**Comment by judewang** [comment]
@GGantulga I suggest take a look at [custom-claims](https://firebase.google.com/docs/auth/admin/custom-claims) of FireBase authentication's admin section. This way we can really grant a user to admin and protect data with database's rules. Even though users can use some hacks to render the component, they can do nothing with our database.
