### ISSUE TITLE
Question: Assigning State

### ISSUE THREAD

**Issue by jamigibbs** [tylermcginnis/react-router-firebase-auth#30]
In `src/components/index.js`, state is being assigned like this:

```
  state = {
    authed: false,
    loading: true,
  }
```

https://github.com/tylermcginnis/react-router-firebase-auth/blob/master/src/components/index.js#L34-L37

But the syntax I'm familiar with is:

```
  constructor(props) {
    super(props);
    this.state = {
        authed: false,
        loading: true,
    };
  }
```

Can someone explain why it's being done like that?

**Comment by tylermcginnis** [comment]
Hey! That syntax is currently a stage 3 proposal (but is supported by create-react-app) and is called "Property Initializers". [Here's](https://michalzalecki.com/react-components-and-class-properties/) a pretty good article I just found that talks about it.
