### ISSUE TITLE
Creds are out in the open in constants.js

### ISSUE THREAD

**Issue by ptums** [tylermcginnis/react-router-firebase-auth#32]
Hey bud,

Love the code example! I have a small suggestion for the app, instead of revealing your API Key, authdomain, and databaseURL. I would mask those with asterisks **s and put a link in the comments to how to get set up firebase and get credentials. I think'll be beneficial to anyone using the app not utilize your creds. 

Shocked that you weren't alerted from github about this.

Well any way, awesome app!

Peter

**Comment by simoneduca** [comment]
I don't think it's a big deal https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public

**Comment by ptums** [comment]
Oh cool did not know that.
