### ISSUE TITLE
Moving to Firebase Version 3+

### ISSUE THREAD

**Issue by jakebresnehan** [tylermcginnis/react-router-firebase-auth#4]
Hey @tylermcginnis!

Just wanted to know if you had any plans on updating the repo to align with the new version of Firebase?

Cheers,
Jake

**Comment by jkomyno** [comment]
+1

**Comment by tylermcginnis** [comment]
Yeah I'll get to it one day. Tons of stuff I have to do before but definitely plan on it

**Comment by lucianotonet** [comment]
Here's my contribution. 
Upgraded to Firebase 3.3.0
https://github.com/tylermcginnis/react-router-firebase-auth/pull/5
@tylermcginnis , What do you think? =]
