### ISSUE TITLE
Async issue

### ISSUE THREAD

**Issue by julienbornstein** [tylermcginnis/react-router-firebase-auth#6]
Hi,
If you :
- log in
- go to dashboard
- refresh the page 

then you will be redirect to login page. 
Dont log in, just click to home, then click to dashboard and here.

Problem : when accessing directrly a secure page (http://127.0.0.1:8080/public/#/dashboard), firebase is reponding after the onEnter function, so you are marked as not logged. Must found a better solution so onEnter function wait for firebase response (success or not but waiting for a response) before return. I'm working on it.

**Comment by tylermcginnis** [comment]
👍🏻

**Comment by julienbornstein** [comment]
First you need to set `state.loggedIn` to `false` if user is not authenticated, to `true` if authenticated and to `null` when authenticated state in unknown (before Firebase response). When firebase response come back, update `state.loggedin` to true or false, but not null. 

``` javascript
firebase.auth().onAuthStateChanged(firebaseUser => {
    this.setState({
        loggedIn: (null !== firebaseUser ? true:false)
    })
    ...
});
```

You need to move this part of code to your main js file to load early in the app, before the router. I use Redux so you probably need to change my code so the global state could be available from the main js file.

then update the requireAuth()

``` javascript
function requireAuth(nextState, replace) {

  // wait Firebase auth response
  (function waitAuthResponse() {
    if (null === state.loggedIn) {
      setTimeout(waitAuthResponse, 100);
    } else {
      if(null === firebase.auth().currentUser) {
        replace({
          pathname: '/login',
          state: { nextPathname: nextState.location.pathname }
        })
      }
    }
  })();

}
```

last change, update the root Route 

``` javascript
 {this.state.loggedIn !== null ? this.props.children:'Auth in progress...'}
```

**Comment by Bonitis** [comment]
Hey I'm running into something similar. I am initializing firebase in a separate config file and importing `firebase.auth()` as `auth` into my routes file. Originally, I had something like this:

``` javascript
<Route
      path="/profile"
      getComponent={(nextState, cb) => {
        auth.onAuthStateChanged((user) => {
          if (user) {
            return require.ensure([], require => {
              cb(null, require('./modules/Profile/Profile').default);
            });
          } else {
            return require.ensure([], require => {
              cb(null, require('./modules/Login/Login').default);
            });
          }
        });
      }}
    />
```

Unfortunately in the short amount of time it takes to load the user, the alternate component renders, which isn't a very good experience. I've tried using `onEnter` and it never seems to work right when using firebase auth. Any luck or progress working on this?

**Comment by Bonitis** [comment]
**Update:** This did not end up working. It made things worse, I just hadn't tested it properly. I'm back where I started.

So this seems to be working for me. Just adding `callback()` inside my `onAuthStateChanged` call does the trick. 

``` javascript
function requireAuth(nextState, replace, callback) {
  auth.onAuthStateChanged((user) => {
    if (!user) {
      replace({
        pathname: '/login',
        state: { nextPathname: nextState.location.pathname },
      });
    }
    callback();
  });
}
```

I'm guessing because the transition is blocked until `callback()` is called. Let me know what you guys think of this and if there is a better solution.

**Comment by sebnun** [comment]
A different solution is to check `localStorage`.
in `authenticated.js` :

```
function (nextState, replace) {
    if (!firebase.auth().currentUser) {
        let hasLocalStorageUser = false;
        for (let key in localStorage) {
            if (key.startsWith("firebase:authUser:")) {
                hasLocalStorageUser = true;
            }
        }
        if (!hasLocalStorageUser) {
            console.log('Attempting to access a secure route. Please authenticate first.');
            replace({
                pathname: '/login',
                state: { nextPathname: nextState.location.pathname }
            });
        }
    }
};

```

from http://stackoverflow.com/questions/37370599/firebase-auth-delayed-on-refresh

**Comment by Bonitis** [comment]
@sebnun this seems to be working for me. I reworked it a bit with some lodashery. My second function here will kick the user back to their previous page if they tried to navigate to `/login` for some reason while they were logged in. Keep in mind that in my case `auth = firebase.auth()`.

``` javascript
function requireAuth(nextState, replace) {
  if (!auth.currentUser) {
    let hasLocalStorageUser = false;
    _.forEach(_.keys(localStorage), (d) => {
      if (d.startsWith('firebase:authUser')) {
        hasLocalStorageUser = true;
      }
    });
    if (!hasLocalStorageUser) {
      replace({
        pathname: '/login',
        state: { nextPathname: nextState.location.pathname },
      });
    }
  }
}

function redirectBack() {
  let hasLocalStorageUser = false;
  _.forEach(_.keys(localStorage), (d) => {
    if (d.startsWith('firebase:authUser')) {
      hasLocalStorageUser = true;
    }
  });
  if (auth.currentUser || hasLocalStorageUser) {
    history.back();
  }
}
```

Do you think it makes any sense to keep an `onAuthStateChanged()` in there somewhere? Such as tacking this onto the end of the `requireAuth()` function?

``` javascript
auth.onAuthStateChanged((user) => {
    if (!user) {
      replace({
        pathname: '/login',
        state: { nextPathname: nextState.location.pathname },
      });
    }
  });
```

I am using Facebook login, so that would allow me to send them to login if their Facebook creds expire (I think!). Would that work or is it unnecessary?

**Comment by Bonitis** [comment]
**Update:** I am having trouble with my code above when navigating to some routes. `localStorage` is not yet available and the page crashes. So here is my fix at the moment. This is slower and not as good, but doesn't crash:

``` javascript
function requireAuth(nextState, replace) {
  const browserStorage = (typeof localStorage === 'undefined') ?
    null : localStorage;
  if (browserStorage) {
    if (!auth.currentUser) {
      let hasBrowserStorageUser = false;
      _.forEach(_.keys(browserStorage), (d) => {
        if (d.startsWith('firebase:authUser')) {
          hasBrowserStorageUser = true;
        }
      });
      if (!hasBrowserStorageUser) {
        replace({
          pathname: '/login',
          state: { nextPathname: nextState.location.pathname },
        });
      }
    }
  } else {
    auth.onAuthStateChanged((user) => {
      if (!user) {
        replace({
          pathname: '/login',
          state: { nextPathname: nextState.location.pathname },
        });
      }
    });
  }
}
```

**Comment by tylermcginnis** [comment]
I just redid everything. Should be fixed.

**Comment by michelalbers** [comment]
@Bonitis Your solution works well for me! Thanks!
