### ISSUE TITLE
Question:  Add new users to /users in your Firebase

### ISSUE THREAD

**Issue by barrymichaeldoyle** [tylermcginnis/react-router-firebase-auth#8]
In the readme there us a feature listed here:

Add new users to /users in your Firebase

Where in the code is this implemented?

**Comment by leonardofaria** [comment]
I think that you're talking about the `handleSubmit` function from file `app/components/login-register/Login.js`.

The `signInWithEmailAndPassword` function finds or creates the user inside Firebase.
